### ISSUE TITLE
Enable Asynchronous Handlers

### ISSUE THREAD

**Issue by Kab1r** [vercel-community/rust#20]
It would be nice if we could have an asynchronous handler for a function. I know you can do this with the Node API.

Ideally, I should be able to pass a handler function that returns a future into the lambda macro.

Alternatively, there could be a separate macro for asynchronous handlers.

**Comment by mike-engel** [comment]
@KabirKwatra I'll take a look at this when I get a chance, but if you have ideas, PRs are welcome

**Comment by srounce** [comment]
[awslabs/aws-lambda-rust-runtime](https://github.com/awslabs/aws-lambda-rust-runtime) supports this already on the master branch but they haven't cut a release [because reasons](https://github.com/awslabs/aws-lambda-rust-runtime/issues/216). The current master branch API has changed since 0.2 but any changes that may need to happen minimal, the API surface of `now_lambda` should be unaffected.

**Comment by leerob** [comment]
Yay, this is supported now!

https://github.com/awslabs/aws-lambda-rust-runtime/releases

**Comment by ecklf** [comment]
Hey we released a new runtime in https://github.com/vercel-community/rust/pull/80 which should now enable this. Happy about every feedback.
